[build]
builder = "Dockerfile"

[deploy]
startCommand = "./mta-server64 -n"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "never"

[[ports]]
port = 22003
protocol = "udp"

[[ports]]
port = 22126
protocol = "tcp"
